name=input("what is Pet's Name? \n\n")
age=input("what is pet's age?\n\n")
animal_type=input("what is pet's Animal Type?\n\n")
toy=input("what is pet's favourite toy?\n\n")
shelter = input("what is the shelter's name?\n\n")
print(f"--ADOPT ME!--\n\n")
print(f"{"="*40}\n\n")
print(f"pet's name is {name}\n\n") 
print(f"pet's age is {age}\n\n")
print(f"pet's Animal Type is {animal_type}\n\n")
print(f"pet's favourite toy is {toy}\n\n")
print(f"Shelter's name is {shelter}\n\n")
print(f"Adoption ID: {name}-{animal_type}-{shelter}")
print(f"{"="*40}\n\n")